### ISSUE TITLE
没有用了

### ISSUE THREAD

**Issue by caomfan** [liqiang0508/Douyin-Sprider#1]

**Comment by HelloAndGoodbye0** [comment]
有什么报错么？目前我这边还行

**Comment by caomfan** [comment]
错误倒是没报。
只是一直在这里面循环
 if len(aweme_list)==0:
        getPost(max_cursor,getsign())

应该是aweme_list一直获取不到。

**Comment by HelloAndGoodbye0** [comment]
我修改了下代码，没获取到会一直尝试去拿aweme_list 所以有个循环。等一会就应该有数据了，不是一运行就会有数据的

**Comment by caomfan** [comment]
这个我清楚，但是它是一直循环，差不多有10分钟左右就会请求报错了。

**Comment by HelloAndGoodbye0** [comment]
啥错

**Comment by caomfan** [comment]
代码更新以后可以了，估计是那个文件引用的问题，我之前也改了。现在有一个问题就是，发布的作品没法下载到无水印的是吗？

**Comment by HelloAndGoodbye0** [comment]
无水印我没研究，看网上说的以前是有无水印的地址，现在没有了，可以用第三方去水印的工具你可以研究下。
